image: alpine/edge
packages:
  - go
  - git
  - make
sources:
  - https://git.sr.ht/~motiejus/undocker
tasks:
  - setup: |
      go install honnef.co/go/tools/cmd/staticcheck@latest
  - test: |
      make -C undocker coverage.html
  - lint: |
      make -C undocker -O -j$(nproc) lint
  - binaries: |
      make -C undocker -O -j$(nproc) sha256sum.txt
      cat undocker/sha256sum.txt
artifacts:
  - undocker/coverage.html
