image: alpine/edge
packages:
  - go
  - git
  - make
sources:
  - https://git.sr.ht/~motiejus/undocker
tasks:
  - setup: |
      go install honnef.co/go/tools/cmd/staticcheck@latest
  - test: |
      make -C undocker coverage.html
  - lint: |
      make -C undocker -j$(nproc) -O lint
  - all: |
      make -C undocker -j$(nproc) -O all
artifacts:
  - undocker/coverage.html
