image: alpine/edge
packages:
  - go
  - git
  - make
  - shellcheck
sources:
  - https://git.sr.ht/~motiejus/undocker
tasks:
  - setup: |
      go install honnef.co/go/tools/cmd/staticcheck@latest
  - built-test-lint: |
      make -C undocker -O -j$(nproc) undocker coverage.html lint
  - usage: |
      # like 'grep -q', but prints output too.
      # | tee /dev/stderr doesn't work on sourcehut workers; permission denied.
      ./undocker/undocker |& awk 'BEGIN{c=1};/Built with /{c=0};{print};END{exit c}'
artifacts:
  - undocker/coverage.html
