image: alpine/edge
packages:
  - go
  - git
  - make
  - shellcheck
sources:
  - https://git.sr.ht/~motiejus/undocker
tasks:
  - setup: |
      go install honnef.co/go/tools/cmd/staticcheck@latest
  - test: |
      make -C undocker coverage.html
  - lint: |
      make -C undocker -O -j$(nproc) lint
  - usage: |
      ./undocker/undocker |& tee /dev/stderr | grep -q "Built with "
artifacts:
  - undocker/coverage.html
