image: alpine/edge
packages:
  - go
  - git
  - make
sources:
  - https://git.sr.ht/~motiejus/undocker
tasks:
  - setup: |
      GOPATH=/usr/local go install honnef.co/go/tools/cmd/staticcheck
  - test: |
      make -C undocker coverage.html
  - lint: |
      make -C undocker lint
artifacts:
  - undocker/coverage.html
