image: alpine/edge
packages:
  - go
sources:
  - https://git.sr.ht/~motiejus/undocker
tasks:
  - test: |
      cd undocker
      go test -cover ./...
  - build-linux-amd64: |
      cd undocker
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o undocker-linux-amd64
  - build-linux-arm64: |
      cd undocker
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o undocker-linux-arm64
  - build-darwin-amd64: |
      cd undocker
      CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o undocker-darwin-amd64
  - build-darwin-arm64: |
      cd undocker
      CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o undocker-darwin-arm64
  - build-windows-amd64: |
      cd undocker
      CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o undocker-windows-amd64.exe
artifacts:
  - undocker/undocker-linux-amd64
  - undocker/undocker-linux-arm64
  - undocker/undocker-darwin-amd64
  - undocker/undocker-darwin-arm64
  - undocker/undocker-windows-amd64.exe
